### PR TITLE
Custom arguments and environment variables.

### LINKED ISSUE #47: NoClassDefFoundError while downloading on Gradle-3.0-milestone-1
Since ProgressLogger was moved the following exception is thrown while downloading

```
Caused by: java.lang.NoClassDefFoundError: Lorg/gradle/logging/ProgressLogger;
	at org.gradle.internal.metaobject.BeanDynamicObject.getMetaClass(BeanDynamicObject.java:139)
	at org.gradle.internal.metaobject.BeanDynamicObject.access$400(BeanDynamicObject.java:55)
	at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.invokeMethod(BeanDynamicObject.java:379)
	at org.gradle.internal.metaobject.BeanDynamicObject.invokeMethod(BeanDynamicObject.java:170)
	at org.gradle.internal.metaobject.ConfigureDelegate.invokeMethod(ConfigureDelegate.java:59)
	at build_bde9ot97vy9vu4gqda0wc6vps$_downloadAndUnzip_closure9.doCall(/Users/zolotov/dev/intellij-plugins/intellij-go/build.gradle:128)
	at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:70)
	at org.gradle.util.ConfigureUtil.configureTarget(ConfigureUtil.java:160)
	at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:106)
	at de.undercouch.gradle.tasks.download.DownloadExtension.configure(DownloadExtension.java:42)
	at de.undercouch.gradle.tasks.download.DownloadExtension.configure(DownloadExtension.java:29)
	at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:104)
	at org.gradle.util.ConfigureUtil$1.execute(ConfigureUtil.java:123)
	at org.gradle.api.internal.plugins.ExtensionsStorage$ExtensionHolder.configure(ExtensionsStorage.java:145)
	at org.gradle.api.internal.plugins.ExtensionsStorage.configureExtension(ExtensionsStorage.java:69)
	at org.gradle.api.internal.plugins.DefaultConvention$ExtensionsDynamicObject.invokeMethod(DefaultConvention.java:215)
	at org.gradle.internal.metaobject.CompositeDynamicObject.invokeMethod(CompositeDynamicObject.java:96)
	at org.gradle.internal.metaobject.MixInClosurePropertiesAsMethodsDynamicObject.invokeMethod(MixInClosurePropertiesAsMethodsDynamicObject.java:30)
	at org.gradle.internal.metaobject.AbstractDynamicObject.invokeMethod(AbstractDynamicObject.java:163)
	at org.gradle.groovy.scripts.BasicScript.methodMissing(BasicScript.java:79)
	at build_bde9ot97vy9vu4gqda0wc6vps.downloadAndUnzip(/Users/zolotov/dev/intellij-plugins/intellij-go/build.gradle:127)
	at build_bde9ot97vy9vu4gqda0wc6vps$_run_closure7.doCall(/Users/zolotov/dev/intellij-plugins/intellij-go/build.gradle:103)
	at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:587)
	at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:568)
	at org.gradle.api.internal.tasks.TaskMutator$1.execute(TaskMutator.java:80)
	at org.gradle.api.internal.tasks.TaskMutator$1.execute(TaskMutator.java:76)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
	... 71 more
```

### PR DESCRIPTION
**Pull request by panekzogen**
Added possibility to set custom arguments and environment variables.

One bug fixed: https://github.com/michel-kraemer/gradle-download-task/issues/47

### CODE REVIEW

**Comment by qliklars** [comment]
Is there a reason for closing but nor merging this PR?
We are very interested in the environment variable support that is added in this PR.
Is there any easy workaround with the current plugin?

File: src/main/groovy/com/ullink/gradle/nunit/NUnit.groovy [hunk 1]
```diff
@@ -31,6 +31,9 @@ class NUnit extends ConventionTask {
     def test
     def testList
 
+    Map<String, Object> custom = [:]
```
Comment (timotei) [inline src/main/groovy/com/ullink/gradle/nunit/NUnit.groovy]: I'd rename this to `extraCommandLineArgs`

**Comment by timotei** [comment]
Sorry for the delay on reviewing this :(

First of all, thanks for the contribution!

For the custom extra arguments, are there any specific ones? Maybe we should add them as properties in the plugin itself instead.

File: src/main/groovy/com/ullink/gradle/nunit/NUnit.groovy [hunk 2]
```diff
@@ -31,6 +31,9 @@ class NUnit extends ConventionTask {
...
+    Map<String, Object> env = [:]
```
Comment (timotei) [inline src/main/groovy/com/ullink/gradle/nunit/NUnit.groovy]: Can you please update the README.md sample, so everybody will know about these two properties?

**Comment by panekzogen** [comment]
Reasons for closing this PR: 
- We have limitation on Gradle version higher than 2.14 with download plugin version lower than 3.1.0 (https://github.com/michel-kraemer/gradle-download-task/issues/49)
- Increasing download plugin version caused new problem. (https://github.com/michel-kraemer/gradle-download-task/issues/58). I have no idea how to fix it.

**Comment by panekzogen** [comment]
I'm interesting in  `/labels
/noshadow
/nologo
/timeout
/output` and `/xml` without prefix. But in my opinion adding extra arguments field is more flexible solution.

**Comment by timotei** [comment]
:+1: from me

**Comment by gluck** [comment]
I'm not fond of generic pass-through variables, as it defeats the purpose of having a plugin in the first place (if all you want is write the nunit command-line yourself, nothing will do a better job as using an `Exec` task directly).
For the options you mention, labels/noshadow/timeout/xml are already available, I'd say that nologo should be set by default, so only /output remains. An option could be added, though the common practice (to my knowledge) is to have UT text report in your build log rather than a separate file.

I assume these options come from migrating from a script build approach ?

**Comment by gluck** [comment]
(note that I upgraded gradle/download/httpclient on master and released 1.9 with it, should fix gradle-related issues)

**Comment by qliklars** [comment]
@gluck : What about the env var support? We are passing environment variables that control the placement of test artifacts in prebuilt C# test assemblies.
Do you have a suggestion for them?

**Comment by gluck** [comment]
Totally okay with that one, I missed the fact it was your pain point or I would have included it in the earlier release sorry.
Feel free to PR just that

**Comment by panekzogen** [comment]
Yes these options from migration.
Finally i added _output option_ and _env variables_. From my point of view _output option_ will not be superfluous.

File: src/main/groovy/com/ullink/gradle/nunit/NUnit.groovy [hunk 3]
```diff
@@ -122,12 +126,21 @@ class NUnit extends ConventionTask {
...
+            project.file(logFolder)
+        else
+            return null
+    }
+
     @OutputFile
     File getTestReportPath() {
         // for the non-default nunit tasks, ensure we write the report in a separate file
-        // TODO: Do we need to supply prefix when user has specified its own report file name?
-        def reportFileNamePrefix = name == 'nunit' ? '' : name
```
Comment (gluck) [inline src/main/groovy/com/ullink/gradle/nunit/NUnit.groovy:167]: any reason to remove this prefix ? in case you have mutliple nunit tasks in your build, they'll have the same report file if you remove it.

File: README.md [hunk 4]
```diff
@@ -41,16 +41,24 @@ It creates a task 'nunit' that may be configured as follows:
         // optional - defaults to FALSE and termines the behavior of the task if the nunit-console.exe program exits
         // abnormally
         ignoreFailures = false
-
+        // optional - specify whether to write test case names to the output
```
Comment (gluck) [inline README.md]: kind'o weird to see this change as it's already on master

File: README.md [hunk 5]
```diff
@@ -41,16 +41,24 @@ It creates a task 'nunit' that may be configured as follows:
...
         // Mapped NUnit-Console Command Line Options
         exclude = 'Database'
         include = 'BaseLine'
         // for NUnit v3+, use _where_ option instead of include/exclude
         framework = 'net-1.1'
-        shadowCopy = true
+        shadowCopy = true        
+        // redirect output to file
+        // additionally you can specify logFolder
+        logFileName = 'TestOutput.log'
```
Comment (gluck) [inline README.md]: did you consider putting a single argument (`outputFile` or something) for both ? reportFolder was split because it's used in other places, not sure we need the same here and it'll be simpler.

File: src/main/groovy/com/ullink/gradle/nunit/NUnit.groovy [hunk 6]
```diff
@@ -215,6 +228,7 @@ class NUnit extends ConventionTask {
         prepareExecute()
 
         def mbr = project.exec {
+            environment env
```
Comment (gluck) [inline src/main/groovy/com/ullink/gradle/nunit/NUnit.groovy]: any idea (I didn't check) if when env is empty this will change the behavior from the previous plugin version (still inherits process env variables right ?)

File: src/main/groovy/com/ullink/gradle/nunit/NUnit.groovy (hunk 3 above)
Comment (panekzogen) [reply src/main/groovy/com/ullink/gradle/nunit/NUnit.groovy:167]: There is no possibility to specify name without prefix. But user still can set the same report file in own tasks.

File: src/main/groovy/com/ullink/gradle/nunit/NUnit.groovy (hunk 6 above)
Comment (panekzogen) [reply src/main/groovy/com/ullink/gradle/nunit/NUnit.groovy]: clarify please

File: README.md (hunk 5 above)
Comment (panekzogen) [reply README.md]: Yes, single argument will be simpler. I'll change this in the next commit.

File: src/main/groovy/com/ullink/gradle/nunit/NUnit.groovy (hunk 6 above)
Comment (timotei) [reply src/main/groovy/com/ullink/gradle/nunit/NUnit.groovy]: What @gluck Is saying is: if `env` returns empty/null, will that change the way the project.exec works? i.e.,: will it work the same as if no `environment` has been specific

**Comment by timotei** [comment]
Btw, you should rebase against latest changes, seems there are some conflicts on `README.md`

**Comment by panekzogen** [comment]
Environment method is based on _Map.putAll()_. That's why empty _env_ does not change execution, but null causes _NullPointerException_. I fixed it.
Integration crashes on _nunit 3.5 test_. What will we do about it?
Sorry for a delay.

**Comment by panekzogen** [comment]
Why don't you merge the request?

File: src/main/groovy/com/ullink/gradle/nunit/NUnit.groovy (hunk 3 above)
Comment (timotei) [reply src/main/groovy/com/ullink/gradle/nunit/NUnit.groovy:167]: @taomWTP Well, in the new change we won't have this prefix anymore by default. How about if the user *does not* specify the report file, we keep the previous behaviour? But even so, I don't see why this change is needed for this PR 🤔

Comment (panekzogen) [reply src/main/groovy/com/ullink/gradle/nunit/NUnit.groovy:167]: Right, this change isn't needed for this PR, but it solves the problem that i mentioned above. I can open another PR for it if you want.
When making this change I was taking into account the fact that if user didn't specify report file, he doesn't really need it and we can follow the nunit default behavior that store all results in _TestResult.xml_.

There is another solution that keeps the previous behavior. It was written in your _TODO_ comment. Namely, prefix won't be used when user specified his own report file name. I think this is more tolerant solution if you want to keep previous behavior. I will do this if you agree.

Comment (timotei) [reply src/main/groovy/com/ullink/gradle/nunit/NUnit.groovy:167]: > When making this change I was taking into account the fact that if user didn't specify report file, he doesn't really need it

I hear you, but we can't be sure we don't break lots of usages out there, that rely on the xml being named by the plugin automatically, based on the task name. That's why I'd say we should aim at keeping a backwards compat behavior if possible and if it doesn't prevent us from evolving. 

@gluck @bcorne Feedback on this?

Comment (panekzogen) [reply src/main/groovy/com/ullink/gradle/nunit/NUnit.groovy:167]: I suppose, that you will agree with new changes.

**Comment by kuniss** [comment]
When do you plan to merge this pull request?
I'm also interested in having the possibility to define environment variables...

BTW, great work! Thank you for the Ullink Gradle plugins!

**Comment by gluck** [comment]
Long overdue, sorry !

**Comment by kuniss** [comment]
Great! Thanks!

I guess some one needs to push a release? 
Version 1.11 is not released yet on plugins.gradle.org ...

Or is on the way? Did not see it on AppVeyor nor Travis.

**Comment by ngyukman** [comment]
will do a release once the fix for #42 is ready, thanks for patient

**Comment by kuniss** [comment]
@ngyukman I saw the release 1.11 is done on GitHub. Thank you!
When do you plan to publish it to https://plugins.gradle.org/plugin/com.ullink.nunit?

**Comment by ngyukman** [comment]
@kuniss sorry that we are having some problem with the release in https://plugins.gradle.org/
but you can reference to the maven repo https://bintray.com/ullink/gradle-plugins/com.ullink.gradle:gradle-nunit-plugin for now, we will fix it once we have resolved the release issue

**Comment by kuniss** [comment]
No problem!

I will wait or use the repo dependency.

Thank you, for coming back with a note!


Am 13.07.2017 um 11:42 schrieb Ng Yuk Man:
